// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCYYlte6ip4E9gbz1auy88M_Zgc-P2u8',
    appId: '1:302486751890:web:4bbb15510a74cb499e344b',
    messagingSenderId: '302486751890',
    projectId: 'sloffee-ai',
    authDomain: 'sloffee-ai.firebaseapp.com',
    storageBucket: 'sloffee-ai.appspot.com',
    measurementId: 'G-P28CR0RD5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzgTj-d1wCKscF__o0okEoTpBAuZS578',
    appId: '1:302486751890:android:e6f226b5e454a0379e344b',
    messagingSenderId: '302486751890',
    projectId: 'sloffee-ai',
    storageBucket: 'sloffee-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtKXhmysYloNSgLhUcLuv07DIu7ExvZmE',
    appId: '1:302486751890:ios:91cea64cf071ce2d9e344b',
    messagingSenderId: '302486751890',
    projectId: 'sloffee-ai',
    storageBucket: 'sloffee-ai.appspot.com',
    iosClientId:
        '302486751890-2r5hass7kb9uaak80r3d1grkhsfkep14.apps.googleusercontent.com',
    iosBundleId: 'com.example.sloffeeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtKXhmysYloNSgLhUcLuv07DIu7ExvZmE',
    appId: '1:302486751890:ios:91cea64cf071ce2d9e344b',
    messagingSenderId: '302486751890',
    projectId: 'sloffee-ai',
    storageBucket: 'sloffee-ai.appspot.com',
    iosClientId:
        '302486751890-2r5hass7kb9uaak80r3d1grkhsfkep14.apps.googleusercontent.com',
    iosBundleId: 'com.example.sloffeeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvCYYlte6ip4E9gbz1auy88M_Zgc-P2u8',
    appId: '1:302486751890:web:6daf6e23db89187c9e344b',
    messagingSenderId: '302486751890',
    projectId: 'sloffee-ai',
    authDomain: 'sloffee-ai.firebaseapp.com',
    storageBucket: 'sloffee-ai.appspot.com',
    measurementId: 'G-PE4PFL56RF',
  );
}
